# Generated by Django 4.2.8 on 2025-04-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rating_alter_review_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'verbose_name': 'Результат анализа', 'verbose_name_plural': 'Результаты анализов'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='model_version',
            field=models.CharField(default='v1.0', max_length=50, verbose_name='Версия модели'),
        ),
        migrations.AddField(
            model_name='review',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='is_fake',
            field=models.BooleanField(verbose_name='Фейковый'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='probability',
            field=models.FloatField(verbose_name='Вероятность'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='reviews.review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(db_index=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('text', 'source')},
        ),
    ]
