# Generated by Django 4.2.8 on 2025-04-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("reviews", "0004_alter_analysisresult_options_alter_review_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("html_content", models.TextField(verbose_name="HTML-контент")),
                ("success", models.BooleanField(verbose_name="Успешно")),
                ("error_message", models.TextField(
                    blank=True, verbose_name="Ошибка")),
            ],
            options={
                "verbose_name": "Лог парсера",
                "verbose_name_plural": "Логи парсера",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParserConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL для парсинга")),
                (
                    "params",
                    models.JSONField(
                        default=dict, verbose_name="Параметры запроса"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                        verbose_name="Расписание (Celery)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфигурация парсера",
                "verbose_name_plural": "Конфигурации парсеров",
            },
        ),
    ]
