# Generated by Django 4.2.8 on 2025-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_debuglog_parserconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_fake',
            field=models.BooleanField(default=False, verbose_name='Фейковый'),
        ),
    ]
