# Generated by Django 4.2.8 on 2025-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reputation',
            field=models.IntegerField(default=0, verbose_name='Репутация'),
        ),
    ]
